In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [42]:
Xtrain=pd.read_csv("Logistic_X_Train.csv")
Ytrain=pd.read_csv("Logistic_Y_Train.csv")

In [43]:
print(Xtrain.shape)
print(Ytrain.shape)

(3000, 3)
(3000, 1)


In [44]:
Xtrain.head()

f1        f2        f3
0 -1.239375  0.749101 -0.528515
1 -1.036070  0.801436 -1.283712
2 -0.615579  1.579521 -1.391927
3  1.335978  1.348651  1.433564
4  0.658925  1.300019  0.571603

In [45]:
Ytrain.head(n=10)

label
0      1
1      1
2      1
3      0
4      0
5      0
6      0
7      0
8      1
9      1

In [46]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [47]:
lr.fit(Xtrain,Ytrain)

c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression()

In [48]:
Xtest=pd.read_csv("Logistic_X_Test.csv")

In [49]:
Xtest.shape

(1000, 3)

In [50]:
Xtest.head()

f1        f2        f3
0 -0.767508 -0.261859 -2.514831
1 -1.241653  1.449001 -0.413089
2  1.925270  1.931761  1.342619
3 -1.298255  1.049761 -0.527319
4 -0.964712  0.938088 -1.186328

In [51]:
y_pred=lr.predict(Xtest)

In [52]:
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

In [53]:
y_train_pred=lr.predict(Xtrain)

In [54]:
y_train_pred

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [55]:
from sklearn import metrics

In [56]:
type(Ytrain)

pandas.core.frame.DataFrame

In [57]:
type(y_pred)

numpy.ndarray

In [58]:
y_pred=pd.DataFrame(data=y_pred,columns=["y"])


In [59]:
type(y_pred)

pandas.core.frame.DataFrame

In [60]:
y_train_pred=pd.DataFrame(data=y_train_pred,columns=["yt"])

In [61]:
print(type(y_train_pred))
print(y_train_pred.shape)
print(y_train_pred.head())

<class 'pandas.core.frame.DataFrame'>
(3000, 1)
   yt
0   1
1   1
2   1
3   0
4   0


In [62]:
y_train_pred=np.array(y_train_pred)
Ytrain=np.array(Ytrain)
acc=float((y_train_pred==Ytrain).sum()/Ytrain.shape[0])

In [63]:
acc=acc*100

In [64]:
print(acc)

99.53333333333333


In [70]:
theta=lr.coef_

In [71]:
theta

array([[-3.92798396,  3.10147056, -2.28040541]])

In [72]:
b=lr.intercept_

In [73]:
b

array([-4.27017148])